version: "3.1"

services:
  mysql:
    command: --default-authentication-plugin=caching_sha2_password
    image: mysql:8.3.0
    container_name: "juicyGreen_mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: plants
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p1234",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"

volumes:
  mysql:
    driver: local
